service: di-onfleet-worker-schedules
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: ${env:PROVIDER_PROFILE}
  stage: ${env:PROVIDER_STAGE}
  region: us-west-2
  environment:
    SNOWFLAKE_USER:
    SNOWFLAKE_PASSWORD:
    ONFLEET_BASE_URL: https://onfleet.com/api/v2
    ONFLEET_API_KEY: ${ssm:/amuse/${self:provider.stage}/onfleet/api/api-key~true}


plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
  - serverless-offline

functions:
  di-onfleet-worker-schedules:
    handler: src/function/di-onfleet-worker-schedules.handler
    events:
      - schedule: cron(0 15 * * ? *)
      - http:
          path: di-onfleet-worker-schedules
          method: GET

